[versions]
kotlin = "2.1.0"
java = "23"

junit-jupiter = "5.11.4"
kotest = "5.9.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
