name: Release
on:
  workflow_dispatch:
jobs:
  gradle:
    name: Gradle
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
    needs: [checks]
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/*
          cache: npm
      - name: Install NPM dependencies
        run: npm clean-install
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload documentation
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        if: ${{ env.RELEASE_SUCCESS == '1' }}
        with:
          path: build/dokka/html
      - name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        if: ${{ env.RELEASE_SUCCESS == '1' }}
        id: deployment
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
