name: Upgrade Gradle Wrapper
on:
  schedule:
    - cron: "0 9 * * mon" # at 09:00 UTC, every monday
  workflow_dispatch:
jobs:
  upgrade-gradle-wrapper:
    name: Upgrade Gradle Wrapper
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Get latest Gradle version
        run: |
          latest_version_json=$(curl --silent 'https://services.gradle.org/versions/current')
          latest_version=$(jq --raw-output '.version' <<< "$latest_version_json")
          echo "latest_version=$latest_version" >> "$GITHUB_ENV"
      - name: Upgrade Gradle Wrapper
        run: |
          ./gradlew wrapper --gradle-version="$latest_version"
          ./gradlew wrapper --gradle-version="$latest_version"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          commit-message: "chore(gradle): bump Gradle Wrapper to ${{ env.latest_version }}"
          branch: "chore/upgrade-gradle-wrapper-${{ env.latest_version }}"
          title: "chore(gradle): bump Gradle Wrapper to ${{ env.latest_version }}"
          body: |
            Bumps the Gradle Wrapper to [${{ env.latest_version }}](https://docs.gradle.org/${{ env.latest_version }}/release-notes.html).
